name: CI/CD Pipeline

# Uncomment the desired trigger event(s) below:

# Manual trigger
# on:
#   workflow_dispatch:

# On every push
on: [push]

# On push or pull request to master branch
# on:
#   push:
#     branches: [master]
#   pull_request:
#     branches: [master]

# Scheduled run every minute (for testing; adjust as needed)
# on:
#   schedule:
#     - cron: '1 * * * *'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install Dependencies
        run: |
          echo "Hello world!"
